import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Project Manager T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="contain-app min-h-screen min-w-screen bg-gradient-to-b from-cyan-900 to-slate-900">
        <div className="w-screen h-screen flex justify-center items-center">
          <Image src={'https://i.pinimg.com/originals/3d/d3/cb/3dd3cb01a4c85204dadb890d522bcaaa.jpg'} alt={"chart"} width={300} height={200} className="rotate-90 rounded-lg shadow-sm shadow-slate-700 bg-gradient-to-br from-zinc-400 to-cyan-900 "/>
        </div>
      </div>
      
    </>
  );
};

export default Home;


